### ISSUE TITLE
xps 13 9350

### ISSUE THREAD

**Issue by AdrienLemaire** [gunzy83/linux-xps13-aur#1]
Hi gunzy,

I see you've been updating your patch for a while now (L321X & l322X are from 2012-2013). I've recently bought a 9350, and was wondering how much work would be required to get multi-touch working properly.
Do you have any recommendation? Is it a good idea to start from your patch?
I'd love to know more about how you got started with your own patch :)

Thanks!

**Comment by gunzy83** [comment]
Hi,

Sorry about the slow reply. I have not looked into what would be required for later models of the XPS13 (I still have a L322X at work and one at home). 

I would start by testing to see the capability of the hardware of the 9350. I see that the 9350 has an Elantech with standard semi-multitouch support (just like the base Cypress driver for the L322X) and the Arch wiki page lists `libinput` support: [Arch Wiki](https://wiki.archlinux.org/index.php/Dell_XPS_13_(9350)#Touchpad). Some members of the forum have reported that that they have gestures working with `libinput` and `libinput-gestures` (see [here](https://bbs.archlinux.org/viewtopic.php?pid=1617669#p1617669). See [here](https://github.com/bulletmark/libinput-gestures) for more details and remember to add yourself to the input group and reboot.

If that does not work you will need create a patch where:

1. the number of slots reported by the driver is larger than 2 (3 or 4)
2. the driver reports those touches so that userland can respond to them (eg drags and pinches)

I got started with this from a patch in Ubuntu that was rejected upstream by the kernel maintainers. Initially it would not work after suspend but I fixed that and just kept updating the kernel in lockstep with the standard Arch kernel when I had time. I have had trouble with `touchegg` and `synaptics` the last 8-9 months or so (diminished my motivition to patch the kernel) but I have recently had success with `libinput` and `libinput-gestures` so I will be keeping things rolling forward and will update the documentation soon as well.

Good luck and let me know how you go with the 9350 (may be looking for my next laptop in a few months time).
